// Offscreen Stack — data source
// All text in CA + EN for language toggle.

window.OS_DATA = {
  nav: {
    ca: ["intro", "sobre", "404", "com funciona", "custom", "contacte"],
    en: ["intro", "about", "404", "how it works", "custom", "contact"],
  },
  hero: {
    ca: {
      kicker: "OFFSCREEN STACK — SS26",
      title: "404:\nnot found,\nbut stitched.",
      lede: "Gorres brodades a mà inspirades en stacks, eines i símbols de la cultura digital. Peces deliberadament imperfectes, fetes per gent que viu una mica massa a prop del navegador.",
      cta1: "Veure la col·lecció",
      cta2: "Demanar una custom",
    },
    en: {
      kicker: "OFFSCREEN STACK — SS26",
      title: "404:\nnot found,\nbut stitched.",
      lede: "Hand-embroidered caps based on stacks, tools and symbols of digital culture. Deliberately imperfect pieces, made by people who live a bit too close to the browser.",
      cta1: "See the collection",
      cta2: "Request a custom",
    },
  },
  terminal: {
    ca: [
      { p: "noa@offscreen", cmd: "ls ./404-collection" },
      { out: "claude-code_framer.cap   cursor_python.cap   figma_react.cap" },
      { out: "terminal_doodle.cap      custom_stack.cap" },
      { p: "noa@offscreen", cmd: "cat about.txt" },
      { out: "sortir de la pantalla sense desconnectar de la tecnologia." },
      { out: "fer una cosa amb les mans. lenta. física. una mica absurda." },
      { p: "noa@offscreen", cmd: "./start --raw --slow" },
      { out: "▓▓▓▓▓▓▓▓▓▓▓░░░░ stitching..." },
      { ok: "ready. not found, but stitched." },
    ],
    en: [
      { p: "noa@offscreen", cmd: "ls ./404-collection" },
      { out: "claude-code_framer.cap   cursor_python.cap   figma_react.cap" },
      { out: "terminal_doodle.cap      custom_stack.cap" },
      { p: "noa@offscreen", cmd: "cat about.txt" },
      { out: "step out of the screen, stay close to the tech." },
      { out: "make something with your hands. slow. physical. a bit absurd." },
      { p: "noa@offscreen", cmd: "./start --raw --slow" },
      { out: "▓▓▓▓▓▓▓▓▓▓▓░░░░ stitching..." },
      { ok: "ready. not found, but stitched." },
    ],
  },
  about: {
    ca: {
      n: "01",
      label: "SOBRE EL PROJECTE",
      title: "Una manera de\ntraduir píxels\na fil.",
      body: [
        "Offscreen Stack neix d'una idea simple: sortir de la pantalla sense desconnectar de la tecnologia.",
        "Després de tantes hores entre eines, prompts i terminals, em venia de gust fer una cosa amb les mans. Lenta. Física. Una mica absurda, també.",
        "No busquen la perfecció industrial. Busquen caràcter. Cada peça manté petites irregularitats pròpies del procés manual — i aquesta imperfecció no és un error, és part del llenguatge del projecte.",
      ],
      pull: "raw embroidery\nfor internet people",
    },
    en: {
      n: "01",
      label: "ABOUT THE PROJECT",
      title: "A way to\ntranslate pixels\ninto thread.",
      body: [
        "Offscreen Stack starts from a simple idea: step out of the screen without disconnecting from tech.",
        "After so many hours among tools, prompts and terminals, I wanted to make something with my hands. Slow. Physical. A bit absurd too.",
        "They don't aim for industrial perfection. They aim for character. Each piece keeps small irregularities from the manual process — that imperfection isn't a bug, it's part of the project's language.",
      ],
      pull: "raw embroidery\nfor internet people",
    },
  },
  collection: {
    ca: {
      n: "02",
      label: "404 COLLECTION",
      intro: "perfection not found. stacks preferits, icones reinterpretades i petits homenatges a internet, traduïts a fil.",
    },
    en: {
      n: "02",
      label: "404 COLLECTION",
      intro: "perfection not found. favorite stacks, reinterpreted icons and small tributes to the internet, translated into thread.",
    },
  },
  pieces: [
    {
      id: "cc_framer",
      title: "Claude Code × Framer",
      stack: ["CC", "FR"],
      cap: "washed navy",
      edition: "8/12",
      price: "€48",
      size: "big",
      accent: "a",
      note: { ca: "dos glifs a la banda frontal. fil carabassa i or.", en: "two glyphs on the front panel. orange & gold thread." },
    },
    {
      id: "cursor_py",
      title: "Cursor × Python",
      stack: ["CR", "PY"],
      cap: "faded black",
      edition: "5/10",
      price: "€48",
      size: "tall",
      accent: "b",
      note: { ca: "stack vertical, petits errors de tensió intencionats.", en: "vertical stack, intentional tension glitches." },
    },
    {
      id: "figma_react",
      title: "Figma × React",
      stack: ["FG", "RC"],
      cap: "bone",
      edition: "3/10",
      price: "€48",
      size: "wide",
      accent: "a",
      note: { ca: "punt satí per la bola; línia contínua a l'àtom.", en: "satin stitch for the dot; continuous line on the atom." },
    },
    {
      id: "terminal",
      title: "Terminal doodles",
      stack: [">_"],
      cap: "washed olive",
      edition: "open",
      price: "€42",
      size: "sm",
      accent: "b",
      note: { ca: "prompt brodat en monospace. peça 'obrida'.", en: "monospace prompt embroidered. 'open' piece." },
    },
    {
      id: "doodle_404",
      title: "404 doodle",
      stack: ["4", "0", "4"],
      cap: "dust pink",
      edition: "2/6",
      price: "€42",
      size: "sm",
      accent: "a",
      note: { ca: "tres glifs, color variable segons lot.", en: "three glyphs, color varies by batch." },
    },
    {
      id: "custom",
      title: "Custom stack",
      stack: ["?", "?", "?"],
      cap: "tu tries",
      edition: "made to order",
      price: "from €62",
      size: "wide",
      accent: "b",
      note: { ca: "2 o 3 símbols del teu stack. temps realistes.", en: "2 or 3 symbols from your stack. realistic lead times." },
    },
  ],
  howItWorks: {
    ca: {
      n: "03",
      label: "COM FUNCIONA",
      items: [
        { tag: "a.", title: "Ready-made", body: "Peces ja fetes, fotografiades i llestes per sortir. Unitats úniques, cada una lleugerament diferent." },
        { tag: "b.", title: "Made to order", body: "Tries un dels dissenys disponibles i el preparo sota comanda. Temps realistes, tirades petites." },
        { tag: "c.", title: "Custom stack", body: "Una versió personalitzada amb 2 o 3 símbols inspirats en el teu stack. Parlem, decidim, broda." },
      ],
    },
    en: {
      n: "03",
      label: "HOW IT WORKS",
      items: [
        { tag: "a.", title: "Ready-made", body: "Already-finished pieces, photographed and ready to ship. Unique units, each slightly different." },
        { tag: "b.", title: "Made to order", body: "You pick one of the available designs and I prepare it on demand. Realistic lead times, small batches." },
        { tag: "c.", title: "Custom stack", body: "A personalised version with 2 or 3 symbols inspired by your stack. We talk, decide, I stitch." },
      ],
    },
  },
  builder: {
    ca: {
      n: "04",
      label: "CUSTOM BUILDER",
      title: "Munta el teu stack.",
      sub: "Tria 2 o 3 símbols. Jo els broda a mà. Pots enviar-me el teu stack real o un que t'hauries inventat.",
      cta: "Enviar proposta",
      placeholder: "Per què aquest stack? (opcional)",
      hint: "tria fins a 3",
    },
    en: {
      n: "04",
      label: "CUSTOM BUILDER",
      title: "Stack yours.",
      sub: "Pick 2 or 3 symbols. I'll stitch them by hand. Send your real stack, or one you'd make up.",
      cta: "Send proposal",
      placeholder: "Why this stack? (optional)",
      hint: "pick up to 3",
    },
  },
  symbols: [
    { k: "CC", n: "Claude Code" }, { k: "CR", n: "Cursor" }, { k: "FG", n: "Figma" },
    { k: "FR", n: "Framer" }, { k: "RC", n: "React" }, { k: "PY", n: "Python" },
    { k: "JS", n: "JavaScript" }, { k: "TS", n: "TypeScript" }, { k: "RB", n: "Ruby" },
    { k: "GO", n: "Go" }, { k: "RS", n: "Rust" }, { k: "SW", n: "Swift" },
    { k: "VS", n: "VS Code" }, { k: "GH", n: "GitHub" }, { k: "LI", n: "Linear" },
    { k: "NT", n: "Notion" }, { k: "SL", n: "Slack" }, { k: "OB", n: "Obsidian" },
    { k: ">_", n: "Terminal" }, { k: "</>", n: "HTML" }, { k: "{ }", n: "JSON" },
    { k: "404", n: "404" }, { k: "∿", n: "wave" }, { k: "◉", n: "dot" },
  ],
  closing: {
    ca: {
      title: "Porta el teu\nunivers digital\nuna mica fora\nde la pantalla.",
      manifesto: [
        "raw embroidery for internet people.",
        "not found, but stitched.",
        "imperfect by design.",
      ],
      cta1: "Explorar la 404",
      cta2: "Demana la teva custom",
    },
    en: {
      title: "Take your\ndigital universe\na little bit\noff-screen.",
      manifesto: [
        "raw embroidery for internet people.",
        "not found, but stitched.",
        "imperfect by design.",
      ],
      cta1: "Explore the 404",
      cta2: "Request your custom",
    },
  },
};
